# Generated by Django 4.2.3 on 2023-07-23 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0002_rename_discription_product_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dates',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='hours',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='mins',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='months',
            field=models.IntegerField(),
        ),
    ]
