# Generated by Django 4.2.3 on 2023-07-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0003_alter_product_dates_alter_product_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ap',
            field=models.TextField(default='AM'),
        ),
        migrations.AddField(
            model_name='product',
            name='years',
            field=models.TextField(default='2023'),
        ),
        migrations.AlterField(
            model_name='product',
            name='dates',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='hours',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='mins',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='months',
            field=models.TextField(),
        ),
    ]
