# Generated by Django 4.2.3 on 2023-07-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0004_product_ap_product_years_alter_product_dates_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ap',
        ),
        migrations.AlterField(
            model_name='product',
            name='mins',
            field=models.TextField(default='00'),
        ),
    ]
