# Generated by Django 4.2.3 on 2023-07-24 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0006_add_item_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_item_done',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
