# Generated by Django 4.2.3 on 2023-07-26 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0008_alter_add_item_done_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='rate_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
