# Generated by Django 4.2.3 on 2023-07-24 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0005_remove_product_ap_alter_product_mins'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_item_done',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.TextField()),
                ('dates', models.TextField()),
                ('months', models.TextField()),
                ('hours', models.TextField()),
                ('mins', models.TextField(default='00')),
                ('years', models.TextField(default='2023')),
            ],
        ),
    ]
